/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_personal_qvoice_MainActivity */

#ifndef _Included_com_personal_qvoice_MainActivity
#define _Included_com_personal_qvoice_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_personal_qvoice_MainActivity_MODE_NORMAL
#define com_personal_qvoice_MainActivity_MODE_NORMAL 0L
#undef com_personal_qvoice_MainActivity_MODE_LUOLI
#define com_personal_qvoice_MainActivity_MODE_LUOLI 1L
#undef com_personal_qvoice_MainActivity_MODE_DASHU
#define com_personal_qvoice_MainActivity_MODE_DASHU 2L
#undef com_personal_qvoice_MainActivity_MODE_JINGSONG
#define com_personal_qvoice_MainActivity_MODE_JINGSONG 3L
#undef com_personal_qvoice_MainActivity_MODE_GAOGUAI
#define com_personal_qvoice_MainActivity_MODE_GAOGUAI 4L
#undef com_personal_qvoice_MainActivity_MODE_KONGLING
#define com_personal_qvoice_MainActivity_MODE_KONGLING 5L
/*
 * Class:     com_personal_qvoice_MainActivity
 * Method:    voiceChangeNative
 * Signature: (ILjava/lang/String;)V
 */
extern "C" JNIEXPORT void JNICALL Java_com_personal_qvoice_MainActivity_voiceChangeNative
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
